version: "3.7"
services:
  my_app:
    build:
      context: ./
      dockerfile: .docker/dev/php/Dockerfile
    container_name: my_app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - app

  my_nginx:
    image: nginx:stable-alpine3.17
    container_name: my_nginx
    restart: unless-stopped
    ports:
      - "8002:80"
    volumes:
      - ./:/var/www
      - ./.docker/dev/nginx:/etc/nginx/conf.d/
    networks:
      - app

  my_mysql:
    image: mysql:8
    container_name: my_mysql
    command: --default-authentication-plugin=mysql_native_password --general_log=ON --bind_address=0.0.0.0
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: my_db
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_PASSWORD: 123456
      MYSQL_USER: user_app
      SERVICE_TAGS: dev
      SERVICE_NAME: my_mysql_service
    ports:
      - "33006:3306"
    volumes:
      - ./.docker/dev/database/dbdata:/var/lib/mysql
      - ./.docker/dev/database/init:/docker-entrypoint-initdb.d
    networks:
      - app

networks:
  app:
    driver: bridge

